### ISSUE TITLE
Action Bar Bug

### ISSUE THREAD

**Issue by breezefps** [PedroJM96/CoreLibBukkit#1]
![image](https://github.com/PedroJM96/CoreLibBukkit/assets/51733120/63e4cc8a-e5b0-44e0-86bf-88e9e0696a23)

Reporting the bug.

**Comment by Tian-MC** [comment]
I have the same errors, it's not a bug, it's a missing library

**Comment by GodDirtman** [comment]
Same here.

**Comment by PedroJM96** [comment]
Fixed in the latest version
