### ISSUE TITLE
 java.lang.NoSuchFieldException: b

### ISSUE THREAD

**Issue by AJXD2** [PedroJM96/CoreLibBukkit#2]
Server logs: https://pastebin.com/aTmmxzEt

The plugin im using: https://www.spigotmc.org/resources/✪-superlobbydeluxe-1-8-8-1-20-x-✪.20400/

This happens whenever fireworks are spawned throught the lobby plugin mentioned above.

**Comment by skyface753** [comment]
Same problem

**Comment by Ksewedo5** [comment]
PufferFish+ (1.20.1) - The problem occurs

**Comment by F4nyuu** [comment]
Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
java.lang.NoSuchFieldException: b

same

**Comment by omegartlx** [comment]
same

**Comment by FelixKawaii** [comment]
Same problem

**Comment by jurienhamaker** [comment]
+1

**Comment by PedroJM96** [comment]
Fixed in the next version
